=== timhunter/ccpc/dds/openccg/grammars/dict.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (C) 2003 University of Edinburgh (Michael White) 
$Revision: 1.4 $, $Date: 2004/12/07 16:19:27 $ 
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
  <xsd:documentation>
    Schema for dict file.
    
    A dict file is a more refined version of a morph file that groups 
    word forms by their stems (and parts of speech) and lists the mappings 
    to lexical categories.  See the grammar build targets in build.xml 
    for how a dict file can be straightforwardly transformed into the 
    morph.xml and lexicon.xml files required by the run-time system.
    
    See morph.xsd for more information on the the mapping between morph 
    items and lexical categories, and on the macros.
  </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="morph.xsd"/>
  
  
  <xsd:element name="dictionary">
    <xsd:annotation>
    <xsd:documentation>
      The root element, containing a list of dictionary entries and macros.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="entry" type="dictEntryType" maxOccurs="unbounded"/>
        <xsd:element ref="macro" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>

  
  <xsd:complexType name="dictEntryType">
    <xsd:annotation>
    <xsd:documentation>
      A dictionary entry includes any number of 'member-of' and 'stem-for' mapping  
      elements, followed by any number of 'word' elements for different word forms.
      The stem and part of speech (pos) attributes are required.
      If there is just a single word form, it can be specified using the 'word' 
      attribute, with the stem as the default.
      The predicate may also be given with the 'pred' attribute, if it 
      differs from the stem.
      Any macros that apply to all of the entry's word forms may also be listed.
      See morph.xsd for info on the (semantic) class and coart(iculation) attributes.
    </xsd:documentation>
    </xsd:annotation>
      <xsd:sequence>
        <xsd:element ref="member-of" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="stem-for" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="word" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    <xsd:attribute name="word" type="token"/>
    <xsd:attribute name="stem" type="token" use="required"/>
    <xsd:attribute name="pos" type="token" use="required"/>
    <xsd:attribute name="pred" type="token"/>
    <xsd:attribute name="macros" type="listOfMacroNames"/>
    <xsd:attribute name="class" type="token"/>
    <xsd:attribute name="coart" type="xsd:boolean"/>
  </xsd:complexType>


  <xsd:element name="member-of">
    <xsd:annotation>
    <xsd:documentation>
      Specifies a mapping from the entry to a family of lexical categories. 
      The 'family' attribute should provide the name of a category family.
      The 'pred' attribute may be used to specify a different predicate 
      to use with this family.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="family" type="token" use="required"/>
      <xsd:attribute name="pred" type="token"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="stem-for">
    <xsd:annotation>
    <xsd:documentation>
      Specifies a mapping from the entry to a particular entry in a family of 
      lexical categories.
      The 'family' and 'entry' attributes should provide the names of a 
      category family and entry therein.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="family" type="token" use="required"/>
      <xsd:attribute name="entry" type="token" use="required"/>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="word">
    <xsd:annotation>
    <xsd:documentation>
      A specific word form, given by the 'form' attribute.
      Any macros that are particular to the word form may be listed.
      Any lexical category families or entries whose mapping should be 
      blocked may also be listed.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="form" type="token" use="required"/>
      <xsd:attribute name="macros" type="listOfMacroNames"/>
      <xsd:attribute name="excluded" type="listOfTokens"/>  
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== timhunter/ccpc/dds/openccg/grammars/worldcup/dict.xml
<?xml version="1.0"?>
<!-- 
Copyright (C) 2003-4 Jason Baldridge and University of Edinburgh (Michael White) 
$Revision: 1.9 $, $Date: 2004/10/05 11:01:48 $ 
-->
<dictionary name="worldcup"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../dict.xsd"
>

  <entry stem="that" pos="Pron">
    <member-of family="Rel"/>
    <member-of family="Comp"/>
  </entry>

  <entry stem="and" pos="Conj">
    <member-of family="Conj"/>
    <stem-for family="Conj" entry="NP-Collective"/>
    <stem-for family="Conj" entry="NP-Distributive-and-Rightward-TR"/>
    <stem-for family="Conj" entry="NP-Distributive-and-Leftward-TR"/>
  </entry>
  <entry stem="or" pos="Conj">
    <member-of family="Conj"/>
    <stem-for family="Conj" entry="NP-Distributive-or-Rightward-TR"/>
    <stem-for family="Conj" entry="NP-Distributive-or-Leftward-TR"/>
  </entry>

  <entry stem="." pred="declare" pos=".">
    <member-of family="FullStop"/>
  </entry>
  <entry stem="?" pred="ask" pos="?">
    <member-of family="QuestionMark"/>
  </entry>

  <entry stem="everyone" pred="every" pos="QNP">
    <member-of family="QuantNP"/>
  </entry>
  <entry stem="who" pos="WhNP">
    <member-of family="WhNP"/>
  </entry>

  <entry stem="a" pos="Det">
    <member-of family="Det"/>
    <word form="a"/>
    <word form="an"/>
  </entry>
  <entry stem="the" pos="Det">
    <member-of family="Det"/>
  </entry>
  
  <entry stem="his" pos="Det" class="PPRO">
    <member-of family="Det"/>
  </entry>
  <entry stem="my" pos="Det" class="PPRO">
    <member-of family="Det"/>
  </entry>
  <entry stem="its" pos="Det" class="PPRO">
    <member-of family="Det"/>
  </entry>
  
  <entry stem="all" pos="QDet">
    <member-of family="QuantDet"/>
  </entry>
  <entry stem="every" pos="QDet">
    <member-of family="QuantDet"/>
  </entry>
  <entry stem="no" pos="QDet">
    <member-of family="QuantDet"/>
  </entry>

  <entry stem="which" pos="Wh">
    <member-of family="WhDet"/>
  </entry>

  <entry stem="up" pos="Prep">
    <member-of family="Particle"/>
  </entry>
  <entry stem="with" pos="Prep">
    <member-of family="Particle"/>
  </entry>
  <entry stem="from" pos="Prep">
    <member-of family="PrepNom"/>
  </entry>
  <entry stem="to" pos="Prep">
    <member-of family="PrepNom"/>
    <member-of family="To-Infinitive"/>
  </entry>
  <entry stem="without" pos="Prep">
    <member-of family="PrepAdv"/>
  </entry>
  <entry stem="'s" pos="Prep"/>
  <entry stem="of" pos="Prep"/>
  <entry stem="about" pos="Prep"/>
  <entry stem="after" pos="Prep"/>
  <entry stem="on" pos="Prep"/>
  <entry stem="for" pos="Prep"/>
  <entry stem="in" pos="Prep"/>
  <entry stem="by" pos="Prep"/>
  <entry stem="between" pos="Prep"/>

  <entry stem="red" pos="Adj" class="COLOR"/>
  <entry stem="yellow" pos="Adj" class="COLOR"/>
  <entry stem="aggressive" pos="Adj"/>
  <entry stem="reckless" pos="Adj"/>
  <entry stem="quick" pos="Adj"/>
  <entry stem="powerful" pos="Adj"/>
  <entry stem="well-deserved" pos="Adj"/>
  <entry stem="first" pos="Adj"/>
  <entry stem="cup" pos="Adj"/>

  <entry stem="today" pos="Adv" class="TEMP_ADV"/>
  <entry stem="yesterday" pos="Adv" class="TEMP_ADV"/>
  <entry word="previously" stem="previous" pos="Adv"/>
  <entry word="skeptically" stem="skeptic" pos="Adv" class="ATT_ADV"/>
  <entry word="joyfully" stem="joyful" pos="Adv" class="ATT_ADV"/>
  <entry word="easily" stem="easy" pos="Adv" class="MANNER_ADV"/>
  <entry word="quickly" stem="quick" pos="Adv" class="MANNER_ADV"/>
  <entry word="skillfully" stem="skillful" pos="Adv" class="MANNER_ADV"/>
  <entry word="angrily" stem="angry" pos="Adv" class="MANNER_ADV"/>

  <entry stem="may" pos="V">
    <member-of family="Modal"/>
  </entry>
  <entry stem="will" pos="V">
    <member-of family="Modal"/>
  </entry>
  <entry stem="should" pos="V">
    <member-of family="Modal"/>
  </entry>
  <entry stem="would" pos="V">
    <member-of family="Modal"/>
  </entry>
  <entry stem="not" pos="V" macros="@nonfin">
    <member-of family="Modal"/>
  </entry>
  
  <entry word="did" stem="do" pos="V" macros="@past">
    <member-of family="Do-Support"/>
  </entry>

  <entry word="celebrated" stem="celebrate" pos="V" macros="@past">
    <member-of family="IV"/>
  </entry>
  <entry stem="cheer" pos="V">
    <member-of family="IV"/>
    <word form="cheer" macros="@nonfin"/>
    <word form="cheered" macros="@past"/>
  </entry>
  <entry stem="come" pos="V">
    <member-of family="IV"/>
    <word form="come" macros="@nonfin"/>
    <word form="came" macros="@past"/>
  </entry>
  <entry stem="leave" pos="V">
    <member-of family="IV"/>
    <word form="leave" macros="@nonfin"/>
    <word form="left" macros="@past"/>
  </entry>
  <entry word="misses" stem="miss" pos="V" macros="@pres @+3rd-agr @sg-agr">
    <member-of family="IV"/>
  </entry>
  <entry stem="score" pos="V">
    <member-of family="IV"/>
    <member-of family="TV"/>
    <word form="score" macros="@nonfin"/>
    <word form="scores" macros="@pres @+3rd-agr @sg-agr"/>
    <word form="scored" macros="@past"/>
  </entry>
  <entry stem="shoot" pos="V">
    <member-of family="IV"/>
    <member-of family="TV"/>
    <word form="shoot" macros="@nonfin"/>
    <word form="shoots" macros="@pres @+3rd-agr @sg-agr"/>
  </entry>
  <entry stem="smile" pos="V">
    <member-of family="IV"/>
    <word form="smile" macros="@nonfin"/>
    <word form="smile" macros="@pres @-3rd-agr"/>
    <word form="smiles" macros="@pres @+3rd-agr @sg-agr"/>
    <word form="smile" macros="@pres @+3rd-agr @pl-agr"/>
    <word form="smiled" macros="@past"/>
  </entry>
  <entry word="stayed" stem="stay" pos="V" macros="@past">
    <member-of family="IV"/>
  </entry>
  <entry stem="win" pos="V">
    <member-of family="IV"/>
    <member-of family="TV"/>
    <word form="won" macros="@past"/>
    <word form="win" macros="@nonfin"/>
  </entry>

  <entry word="astonished" stem="astonish" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry stem="beat" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry word="blocked" stem="block" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry stem="defeat" pos="V">
    <member-of family="TV"/>
    <word form="defeat" macros="@nonfin"/>
    <word form="defeated" macros="@past"/>
  </entry>
  <entry word="enjoying" stem="enjoy" pos="V" macros="@gerund">
    <member-of family="TV"/>
  </entry>
  <entry word="hosted" stem="host" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry word="kicked" stem="kick" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry stem="meet" pos="V">
    <member-of family="TV"/>
    <word form="meet" macros="@nonfin"/>
    <word form="met" macros="@past"/>
  </entry>
  <entry stem="play" pos="V">
    <member-of family="TV"/>
    <word form="play" macros="@nonfin"/>
    <word form="played" macros="@past"/>
  </entry>
  <entry word="read" stem="read" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry word="saw" stem="see" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry stem="support" pos="V" macros="@nonfin">
    <member-of family="TV"/>
  </entry>
  <entry word="threw" stem="throw" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>
  <entry word="watched" stem="watch" pos="V" macros="@past">
    <member-of family="TV"/>
  </entry>

  <entry stem="return" pos="V" macros="@pp-from">
    <member-of family="TV-Motion"/>
    <word form="return" macros="@nonfin"/>
    <word form="returned" macros="@past"/>
  </entry>
  <entry stem="travel" pos="V" macros="@pp-to">
    <member-of family="TV-Motion"/>
    <word form="travel" macros="@nonfin"/>
    <word form="traveled" macros="@past"/>
  </entry>

  <entry word="knew" stem="know" pos="V" macros="@past">
    <member-of family="TV-Scomp"/>
  </entry>
  <entry word="predicted" stem="predict" pos="V" macros="@past">
    <member-of family="TV-Scomp"/>
  </entry>
  <entry word="said" stem="say" pos="V" macros="@past">
    <member-of family="TV-Scomp"/>
  </entry>
  <entry word="thought" stem="think" pos="V" macros="@past">
    <member-of family="TV-Scomp"/>
  </entry>

  <entry word="picked" stem="pick-up" pos="V" macros="@past @prt-up">
    <member-of family="TV-Phrasal"/>
  </entry>
  <entry stem="tie-with" pos="V" macros="@prt-with">
    <member-of family="TV-PrepComplement"/>
    <word form="tie" macros="@nonfin "/>
    <word form="tied" macros="@past"/>
  </entry>
  
  <entry word="bought" stem="buy" pos="V" macros="@past">
    <member-of family="DTV"/>
  </entry>
  <entry stem="give" pos="V">
    <member-of family="DTV"/>
    <word form="give" macros="@nonfin"/>
    <word form="gives" macros="@pres @+3rd-agr @sg-agr"/>
    <word form="gave" macros="@past"/>
  </entry>
  <entry word="offered" stem="offer" pos="V" macros="@past">
    <member-of family="DTV"/>
  </entry>

  <entry stem="persuade" pos="V">
    <member-of family="ObjectControl"/>
    <word form="persuade" macros="@nonfin"/>
    <word form="persuades" macros="@pres @+3rd-agr @sg-agr"/>
    <word form="persuaded" macros="@past"/>
  </entry>

  <entry stem="shot" pos="N" macros="@sg"/>
  <entry stem="ball" pos="N" macros="@sg"/>
  <entry stem="cup" pos="N" macros="@sg"/>
  <entry stem="friend" pos="N" macros="@sg"/>
  <entry stem="family" pos="N" macros="@sg"/>
  <entry stem="victory" pos="N" macros="@sg"/>
  <entry stem="ticket" pos="N">
    <word form="ticket" macros="@sg"/>
    <word form="tickets" macros="@pl"/>
  </entry>
  <entry stem="book" pos="N" macros="@sg"/>
  <entry stem="card" pos="N" macros="@sg"/>
  <entry stem="goal" pos="N">
    <word form="goal" macros="@sg"/>
    <word form="goals" macros="@pl"/>
  </entry>
  <entry stem="referee" pos="N" macros="@sg"/>
  <entry stem="team" pos="N">
    <word form="team" macros="@sg"/>
    <word form="teams" macros="@pl"/>
  </entry>
  <entry stem="game" pos="N">
    <word form="game" macros="@sg"/>
