=== timhunter/ccpc/dds/openccg/grammars/grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (C) 2003-4 University of Edinburgh (Michael White) 
$Revision: 1.9 $, $Date: 2007/06/24 04:13:06 $ 
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
  <xsd:documentation>
    Schema for grammar file.
    
    A grammar file lists the lexicon, morphology and rules files, 
    and optionally lists the types file and sequences of 
    XSLT transformations to use in loading/saving LFs from/to XML.
    It may also specify a custom list of features to use with 
    supertag names, a custom tokenizer, and/or list semantic classes to 
    replace words with for language models.
  </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="tokens.xsd"/>

  <xsd:element name="grammar">
    <xsd:annotation>
    <xsd:documentation>
      The root element.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="lexicon" type="fileType"/>
        <xsd:element name="morphology" type="fileType"/>
        <xsd:element name="rules" type="rulesType"/>
        <xsd:element name="types" type="fileType" minOccurs="0"/>
        <xsd:element name="supertags" type="supertagsType" minOccurs="0"/>
        <xsd:element name="tokenizer" type="tokenizerType" minOccurs="0"/>
        <xsd:element name="LF-from-XML" type="transformList" minOccurs="0"/>
        <xsd:element name="LF-to-XML" type="transformList" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:complexType name="fileType">
    <xsd:annotation>
    <xsd:documentation>
      An element with a file attribute specifying a filename.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="file" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="rulesType">
    <xsd:annotation>
    <xsd:documentation>
      An element with a file attribute specifying a filename 
      for the rules file, plus an optional combosfile attribute 
      giving the filename for the list of observed supercat-rule 
      combos.  The format of the combos file is one combo per line, 
      where each combo is either a supertag and a rule name, or a 
      pair of supertags and a rule name, separated by single spaces.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexContent>
      <xsd:extension base="fileType">
        <xsd:attribute name="combosfile" type="xsd:string"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="supertagsType">
    <xsd:annotation>
    <xsd:documentation>
      An element which gives the features to use in constructing 
      supertag names.  The feature names are given as a space-delimited list 
      in the feats attribute.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="feats" type="listOfTokens" use="required"/>
  </xsd:complexType>
  
  <xsd:complexType name="tokenizerType">
    <xsd:annotation>
    <xsd:documentation>
      An element which gives the fully qualified class name for 
      a custom tokenizer, and/or lists semantic classes to replace words 
      with for language models.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:attribute name="classname" type="xsd:string"/>
    <xsd:attribute name="replacement-sem-classes" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="transformList">
    <xsd:annotation>
    <xsd:documentation>
      Specifies a sequence of XSLT transformations.
    </xsd:documentation>
    </xsd:annotation>
      <xsd:sequence>
        <xsd:element name="transform" type="fileType" maxOccurs="unbounded"/>
      </xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== timhunter/ccpc/dds/openccg/grammars/routes/grammar.xml
<?xml version="1.0"?>
<!-- 
This grammar contains a lexicon and categories for giving route directions.

Copyright (C) 2006 Michael White
$Revision: 1.2 $, $Date: 2006/05/20 20:34:16 $ 
-->

<grammar name="routes"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../grammar.xsd"
>

  <lexicon file="lexicon.xml"/>
  <morphology file="morph.xml"/>
  <rules file="rules.xml"/>
  <types file="types.xml"/>
  <tokenizer replacement-sem-classes="direction landmark num ord person place road turn"/>

  <LF-from-XML>
    <transform file="../treeify-lists.xsl"/>
    <transform file="../convert-to-hlds.xsl"/>
    <transform file="../core-en/add-chunks.xsl"/>
  </LF-from-XML>

  <LF-to-XML>
    <transform file="../core-en/raise-nodes.xsl"/>
    <transform file="../convert-to-graph.xsl"/>
    <transform file="../simplify-lists.xsl"/>
  </LF-to-XML>

</grammar>

=== timhunter/ccpc/dds/openccg/grammars/comic/grammar.xml
<?xml version="1.0"?>
<!-- 
Copyright (C) 2003-4 University of Edinburgh (Michael White) 
$Revision: 1.8 $, $Date: 2004/11/19 10:59:05 $ 
-->
<grammar name="comic"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../grammar.xsd"
>

  <lexicon file="lexicon.xml"/>
  <morphology file="morph.xml"/>
  <rules file="rules.xml"/>
  <types file="types.xml"/>
  <tokenizer replacement-sem-classes="amt colour colour_prop 
    date decoration manufacturer num quality series time"/>

  <LF-from-XML>
    <transform file="../core-en/derive-features.xsl"/>
    <transform file="../treeify-lists.xsl"/>
    <transform file="../convert-to-hlds.xsl"/>
    <transform file="../core-en/add-chunks.xsl"/>
  </LF-from-XML>

  <LF-to-XML>
    <transform file="../core-en/raise-nodes.xsl"/>
    <transform file="../convert-to-graph.xsl"/>
    <transform file="../simplify-lists.xsl"/>
    <transform file="../core-en/drop-features.xsl"/>
  </LF-to-XML>

</grammar>

=== timhunter/ccpc/dds/openccg/grammars/worldcup/grammar.xml
<?xml version="1.0"?>
<!-- 
Copyright (C) 2003-4 University of Edinburgh (Michael White) 
$Revision: 1.4 $, $Date: 2005/03/22 21:16:45 $ 
-->
<grammar name="worldcup"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../grammar.xsd"
>

  <lexicon file="lexicon.xml"/>
  <morphology file="morph.xml"/>
  <rules file="rules.xml"/>
  <tokenizer replacement-sem-classes="ATT_ADV COLOR COUNTRY 
    MANNER_ADV PERSON PLACE TEMP_ADV"/>

  <LF-from-XML>
    <transform file="../convert-to-hlds.xsl"/>
    <transform file="add-chunks.xsl"/>
  </LF-from-XML>

  <LF-to-XML>
    <transform file="raise-nodes.xsl"/>
    <transform file="../convert-to-graph.xsl"/>
  </LF-to-XML>

</grammar>

=== timhunter/ccpc/dds/openccg/grammars/flights/grammar.xml
<?xml version="1.0"?>
<!-- 
Copyright (C) 2003-5 University of Edinburgh (Michael White) 
$Revision: 1.9 $, $Date: 2005/07/22 21:09:23 $ 
-->
<grammar name="flights"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../grammar.xsd"
>

  <lexicon file="lexicon.xml"/>
  <morphology file="morph.xml"/>
  <rules file="rules.xml"/>
  <types file="types.xml"/>
  <tokenizer replacement-sem-classes="airline airport amt city date dur
    fareclass num person scalar time timeframe"/>

  <LF-from-XML>
    <transform file="../core-en/derive-features.xsl"/>
    <transform file="../treeify-lists.xsl"/>
    <transform file="../convert-to-hlds.xsl"/>
    <transform file="../core-en/add-chunks.xsl"/>
  </LF-from-XML>

  <LF-to-XML>
    <transform file="../core-en/raise-nodes.xsl"/>
    <transform file="../convert-to-graph.xsl"/>
    <transform file="../simplify-lists.xsl"/>
    <transform file="../core-en/drop-features.xsl"/>
  </LF-to-XML>

</grammar>
