=== timhunter/ccpc/dds/openccg/grammars/morph.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (C) 2003 University of Edinburgh (Michael White) 
$Revision: 1.9 $, $Date: 2004/12/07 12:00:39 $ 
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
  <xsd:documentation>
    Schema for morph file.
    
    A morph file lists all the known word forms (morph items) together with 
    their stems, parts of speech, semantic classes, associated macros, and 
    excluded lexical categories.
    
    The part of speech is used to help determine the mapping between morph 
    items and lexical categories.  A morph item is automatically associated 
    with all open families with matching parts of speech.  With closed 
    families, the morph item's stem must be listed as a family member, 
    and the parts of speech must match.  It is also possible to exclude 
    certain lexical category entries or families, by including the entry 
    name, qualified entry name or family name in the morph item's list of 
    excluded lexical categories.
    
    NB: A limitation of the current implementation is that the mapping between  
    morph items and open families can only be done with the stem as the predicate; 
    to use different predicates, closed families must be used.

    Semantic classes may also be given, for n-gram ranking purposes, and for 
    restricting the unification of nominals to compatible types, specified 
    in the types file.  When a category is instantiated, the semantic class 
    is assigned to the nominal var(s) for the proposition with the reserved name 
    '[*DEFAULT*]'.  The types of all nominal vars are then propagated to all 
    other nominal vars with the same name, throughout the category.

    The macros are used to add features or semantic predications to a lexical 
    category that depend on the particular morph item (e.g. tense, number, case, etc.).
  </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="categories.xsd"/>
  
  <xsd:element name="morph">
    <xsd:annotation>
    <xsd:documentation>
      The root element, containing a list of entries (morph items) and macros.
      Each macro must have a unique name.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="entry" maxOccurs="unbounded"/>
        <xsd:element ref="macro" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:unique name="macroNameUniqueness">
      <xsd:selector xpath="macro"/>
      <xsd:field    xpath="@name"/>
    </xsd:unique>
  </xsd:element>

  <xsd:element name="entry">
    <xsd:annotation>
    <xsd:documentation>
      A morph item, with its word form, stem, part of speech, and optional semantic class, 
      associated macros, and excluded lexical categories.  The stem defaults to word form.
      At run time, when the grammar is loaded, a cross-reference check is 
      performed on the names in the lists of associated macros and excluded 
      lexical categories.
      
      The coart flag indicates that this entry is a coarticulation, eg a pitch accent, 
      gesture, or other word-associated element.  With coarticulations, the word form 
      should be one or more attribute-value pairs, with attributes and values separated 
      by hyphens, and multiple pairs separated by colons.  When multiple attribute-value 
      pairs are given, only the first one is used for indexing purposes.  An identifying 
      value for the stem should also be given, eg *accent* for a pitch accent.
      
      NB: Lexical attributes supplied by coarticulations must be done so uniformly; that 
      is, they cannot appear already on some lexical items.  Also, when there are 
      multipled, independent coarticulations, they must supply disjoint sets of lexical 
      attributes, and their categories must be capable of applying in any order.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:attribute name="word" type="token" use="required"/>
      <xsd:attribute name="stem" type="token"/>
      <xsd:attribute name="pos" type="token" use="required"/>
      <xsd:attribute name="class" type="token"/>
      <xsd:attribute name="macros" type="listOfMacroNames"/>
      <xsd:attribute name="excluded" type="listOfTokens"/>  
      <xsd:attribute name="coart" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="macro">
    <xsd:annotation>
    <xsd:documentation>
      A named macro, with a set of features and/or semantic predications to add to
      a lexical category.
      
      The features are given by feature structure declarations, where the id is used 
      to indicate where the features are to be added (i.e., to the feature structure 
      of which atomic category).
      
      The semantic predications are given in an 'lf' element; at run time, these HLDS 
      predications are flattened and added to any predications already present in 
      the lexical category.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="fs" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element name="lf" type="hldsPreds" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="macroName" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="macroName">
    <xsd:annotation>
    <xsd:documentation>
      Macro names begin with @ (for historical reasons) and are followed 
      by at least one non-whitespace character.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="@\S+"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="listOfMacroNames">
    <xsd:list itemType="macroName"/>
  </xsd:simpleType>

</xsd:schema>

=== timhunter/ccpc/dds/openccg/grammars/mini-inuit/morph.xml
<?xml version="1.0" encoding="UTF-8"?>
<morph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../morph.xsd" name="Inuit">
  <entry pos="V" word="qitissallutik" stem="qiti"/>
  <entry pos="V" word="kamat"/>
  <entry pos="V" word="niriursuipput" stem="niriursui"/>
  <entry pos="V" word="tugu"/>
  <entry pos="V" word="ikiussallugu" stem="ikiu"/>
  <entry pos="NP" word="miiqqat"/>
  <entry pos="NP" word="miiraq"/>
  <entry pos="NP" word="Juuna"/>
  <entry pos="NP" word="Piita"/>
  <entry pos="NP" word="nanuq"/>
  <entry pos="Affix" word="p" macros="@erg"/>
  <entry pos="Affix" word="taa" stem="ta"/>
  <entry pos="Affix" word="tuq" stem="ta"/>
  <macro name="@erg">
    <fs id="0" attr="case" val="a-case"/>
  </macro>
</morph>

=== timhunter/ccpc/dds/openccg/grammars/mini-english/morph.xml
<?xml version="1.0" encoding="UTF-8"?>
<morph xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../morph.xsd" name="English">
  <entry word="and" pos="Conj"/>
  <entry word="or" pos="Conj"/>
  <entry word="that" pos="RelPro"/>
  <entry pos="Det" word="a"/>
  <entry pos="Det" word="an" stem="a"/>
  <entry word="the" pos="Det"/>
  <entry word="his" pos="Det"/>
  <entry word="my" pos="Det"/>
  <entry word="its" pos="Det"/>
  <entry word="to" pos="Prep"/>
  <entry word="celebrated" stem="celebrate" pos="V" macros="@past"/>
  <entry pos="V" word="cheer" macros="@nonfin"/>
  <entry pos="V" word="cheered" stem="cheer" macros="@past"/>
  <entry pos="V" word="come" macros="@nonfin"/>
  <entry pos="V" word="came" stem="come" macros="@past"/>
  <entry pos="V" word="leave" macros="@nonfin"/>
  <entry pos="V" word="left" stem="leave" macros="@past"/>
  <entry word="misses" stem="miss" pos="V" macros="@pres @+3rd-agr @sg-agr"/>
  <entry pos="V" word="score" macros="@nonfin"/>
  <entry pos="V" word="scores" stem="score" macros="@pres @+3rd-agr @sg-agr"/>
  <entry pos="V" word="scored" stem="score" macros="@past"/>
  <entry pos="V" word="shoot" macros="@nonfin"/>
  <entry pos="V" word="shoots" stem="shoot" macros="@pres @+3rd-agr @sg-agr"/>
  <entry pos="V" word="smile" macros="@nonfin"/>
  <entry pos="V" word="smile" macros="@pres @-3rd-agr"/>
  <entry pos="V" word="smiles" stem="smile" macros="@pres @+3rd-agr @sg-agr"/>
  <entry pos="V" word="smile" macros="@pres @+3rd-agr @pl-agr"/>
  <entry pos="V" word="smiled" stem="smile" macros="@past"/>
  <entry word="stayed" stem="stay" pos="V" macros="@past"/>
  <entry pos="V" word="won" stem="win" macros="@past"/>
  <entry pos="V" word="win" macros="@nonfin"/>
  <entry word="astonished" stem="astonish" pos="V" macros="@past"/>
  <entry word="beat" pos="V" macros="@past"/>
  <entry word="blocked" stem="block" pos="V" macros="@past"/>
  <entry pos="V" word="defeat" macros="@nonfin"/>
  <entry pos="V" word="defeated" stem="defeat" macros="@past"/>
  <entry word="hosted" stem="host" pos="V" macros="@past"/>
  <entry word="kicked" stem="kick" pos="V" macros="@past"/>
  <entry pos="V" word="meet" macros="@nonfin"/>
  <entry pos="V" word="met" stem="meet" macros="@past"/>
  <entry word="played" stem="play" pos="V" macros="@past"/>
  <entry word="read" stem="read" pos="V" macros="@past"/>
  <entry word="punched" stem="punch" pos="V" macros="@past"/>
  <entry word="studied" stem="study" pos="V" macros="@past"/>
  <entry word="fell-down" stem="fall-down" pos="V" macros="@past"/>
  <entry word="exercise" stem="exercise" pos="V"/>
  <entry word="see" stem="see" pos="V" macros="@past"/>
  <entry word="support" pos="V" macros="@nonfin"/>
  <entry word="threw" stem="throw" pos="V" macros="@past"/>
  <entry word="watched" stem="watch" pos="V" macros="@past"/>
  <entry pos="V" word="give" macros="@nonfin"/>
  <entry pos="V" word="gives" stem="give" macros="@pres @+3rd-agr @sg-agr"/>
  <entry pos="V" word="gave" stem="give" macros="@past"/>
  <entry word="offered" stem="offer" pos="V" macros="@past"/>
  <entry word="persuaded" stem="persuade" pos="V" macros="@past"/>
  <entry word="promised" stem="promise" pos="V" macros="@past"/>
  <entry word="shot" pos="N" macros="@sg"/>
  <entry word="doctor" pos="N" macros="@sg"/>
  <entry word="patient" pos="N" macros="@sg"/>
  <entry word="book" pos="N" macros="@sg"/>
  <entry word="ball" pos="N" macros="@sg"/>
  <entry word="cup" pos="N" macros="@sg"/>
  <entry word="friend" pos="N" macros="@sg"/>
  <entry word="family" pos="N" macros="@sg"/>
  <entry word="victory" pos="N" macros="@sg"/>
  <entry pos="N" word="ticket" macros="@sg"/>
  <entry pos="N" word="tickets" stem="ticket" macros="@pl"/>
  <entry word="card" pos="N" macros="@sg"/>
  <entry pos="N" word="goal" macros="@sg"/>
  <entry pos="N" word="goals" stem="goal" macros="@pl"/>
  <entry word="referee" pos="N" macros="@sg"/>
  <entry pos="N" word="team" macros="@sg"/>
  <entry pos="N" word="teams" stem="team" macros="@pl"/>
  <entry pos="N" word="game" macros="@sg"/>
  <entry pos="N" word="games" stem="game" macros="@pl"/>
  <entry word="fan" pos="N" macros="@sg"/>
  <entry word="final" pos="N" macros="@sg"/>
  <entry word="field" pos="N" macros="@sg"/>
  <entry word="stadium" pos="N" macros="@sg"/>
  <entry word="country" pos="N" macros="@sg"/>
  <entry word="detractor" pos="N" macros="@sg"/>
  <entry pos="N" word="player" macros="@sg"/>
  <entry pos="N" word="players" stem="player" macros="@pl"/>
  <entry word="I" pos="NNP" macros="@-3rd @sg"/>
  <entry word="me" pos="NNP" macros="@-3rd @sg"/>
  <entry word="he" pos="NNP" macros="@sg"/>
  <entry word="her" pos="NNP" macros="@sg"/>
  <entry word="him" pos="NNP" macros="@sg"/>
  <entry word="it" pos="NNP" macros="@sg"/>
  <entry word="you" pos="NNP" macros="@-3rd"/>
  <entry word="Spain" pos="NNP" macros="@sg"/>
  <entry word="Germany" pos="NNP" macros="@sg"/>
  <entry word="Brazil" pos="NNP" macros="@sg"/>
  <entry word="Turkey" pos="NNP" macros="@sg"/>
  <entry word="China" pos="NNP" macros="@sg"/>
  <entry word="Paraguay" pos="NNP" macros="@sg"/>
  <entry word="John" pos="NNP" macros="@sg"/>
  <entry word="Mary" pos="NNP" macros="@sg"/>
  <entry word="Sue" pos="NNP" macros="@sg"/>
  <entry word="Joao" pos="NNP" macros="@sg"/>
  <entry word="Maria" pos="NNP" macros="@sg"/>
  <entry word="Bill" pos="NNP" macros="@sg"/>
  <entry word="Ronaldo" pos="NNP" macros="@sg"/>
  <entry word="Ronaldinho" pos="NNP" macros="@sg"/>
  <entry word="Rivaldo" pos="NNP" macros="@sg"/>
  <entry word="Marcos" pos="NNP" macros="@sg"/>
  <entry word="Kahn" pos="NNP" macros="@sg"/>
  <entry word="Unsal" pos="NNP" macros="@sg"/>
  <macro name="@+3rd-agr">
    <fs id="1" attr="3rd" val="+"/>
    <fs id="2" attr="3rd" val="+"/>
  </macro>
  <macro name="@-3rd">
    <fs id="1" attr="3rd" val="-"/>
    <fs id="2" attr="3rd" val="-"/>
  </macro>
  <macro name="@-3rd-agr">
    <fs id="1" attr="3rd" val="-"/>
    <fs id="2" attr="3rd" val="-"/>
  </macro>
  <macro name="@sg">
    <fs id="2" attr="num" val="sg"/>
    <lf>
      <satop nomvar="X">
        <diamond mode="num">
          <prop name="sg"/>
        </diamond>
      </satop>
    </lf>
  </macro>
  <macro name="@sg-agr">
    <fs id="1" attr="num" val="sg"/>
    <fs id="2" attr="num" val="sg"/>
  </macro>
  <macro name="@pl">
    <fs id="2" attr="num" val="pl"/>
    <lf>
      <satop nomvar="X">
        <diamond mode="num">
          <prop name="pl"/>
        </diamond>
      </satop>
    </lf>
  </macro>
  <macro name="@pl-agr">
    <fs id="1" attr="num" val="pl"/>
    <fs id="2" attr="num" val="pl"/>
  </macro>
  <macro name="@pp-from">
    <fs id="3" attr="lex" val="from"/>
  </macro>
  <macro name="@pp-to">
    <fs id="3" attr="lex" val="to"/>
  </macro>
  <macro name="@prt-up">
    <fs id="4" attr="lex" val="up"/>
  </macro>
  <macro name="@prt-with">
    <fs id="4" attr="lex" val="with"/>
  </macro>
  <macro name="@gerund">
    <fs id="1" attr="vform" val="ger"/>
  </macro>
  <macro name="@nonfin">
    <fs id="1" attr="vform" val="non-fin"/>
  </macro>
  <macro name="@finite">
    <fs id="1">
      <feat attr="vform" val="fin"/>
    </fs>
  </macro>
  <macro name="@past">
    <lf>
      <satop nomvar="E">
        <diamond mode="tense">
          <prop name="past"/>
        </diamond>
      </satop>
    </lf>
  </macro>
  <macro name="@pres">
    <lf>
      <satop nomvar="E">
        <diamond mode="tense">
          <prop name="pres"/>
        </diamond>
      </satop>
    </lf>
  </macro>
</morph>
