=== timhunter/ccpc/dds/openccg/grammars/types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (C) 2003 Gunes Erkan
$Revision: 1.2 $, $Date: 2003/08/26 09:58:19 $ 
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:annotation>
  <xsd:documentation>
    Schema for type hierarchy file.

    A type hierarchy file specifies the hierarchy of simple types which
    constitute the domain of syntactic feature values.
  </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="tokens.xsd"/>

  <xsd:element name="types">
    <xsd:annotation>
    <xsd:documentation>
      The root element, containing a list of type entries.
      Each type must have a unique name.
    </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="type" maxOccurs="unbounded">
          <xsd:annotation>
          <xsd:documentation>
            A simple type, with its name and immediate parents in the hierarchy.
            Parents are specified as a space-separated list of type names.
            Parents attribute is optional and defaults to the built-in type "top".
            Only the immediate parents should be specified. 
            The whole hierarchy is constructed during the initial grammar loading process.
          </xsd:documentation>
          </xsd:annotation>
          <xsd:complexType>
            <xsd:attribute name="name" type="token" use="required"/>
            <xsd:attribute name="parents" type="listOfTokens"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>
    <xsd:unique name="typeNameUniqueness">
      <xsd:selector xpath="type"/>
      <xsd:field    xpath="@name"/>
    </xsd:unique>
  </xsd:element>
</xsd:schema>

=== timhunter/ccpc/dds/openccg/grammars/flights/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2003-4 University of Edinburgh (Michael White)
$Revision: 1.15 $, $Date: 2006/12/29 19:35:54 $ 
-->
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="flights" xsi:noNamespaceSchemaLocation="../types.xsd">
  <!-- form vals -->
  <type name="form-vals"/>
  <type name="dcl-base" parents="form-vals"/>
  <type name="dcl" parents="dcl-base"/>
  <type name="fronted" parents="dcl-base"/>
  <type name="q-base" parents="form-vals"/>
  <type name="q" parents="q-base"/>
  <type name="wh" parents="q-base"/>
  <type name="base" parents="form-vals"/>
  <type name="emb" parents="form-vals"/>
  <type name="inf" parents="form-vals"/>
  <type name="adj" parents="form-vals"/>
  <type name="ng" parents="form-vals"/>
  <!-- person vals (nb: could merge this with number vals) -->
  <type name="pers-vals"/>
  <type name="3rd" parents="pers-vals"/>
  <type name="non-3rd" parents="pers-vals"/>
  <type name="1st" parents="non-3rd"/>
  <type name="2nd" parents="non-3rd"/>
  <!-- number vals -->
  <type name="num-vals"/>
  <type name="sg-or-mass" parents="num-vals"/>
  <type name="sg" parents="sg-or-mass"/>
  <type name="pl-or-mass" parents="num-vals"/>
  <type name="pl" parents="pl-or-mass"/>
  <type name="mass" parents="sg-or-mass pl-or-mass"/>
  <!-- ontological sorts (adapted in part from WordNet 2.0) -->
  <type name="sem-obj"/>
  <type name="abstraction" parents="sem-obj"/>
  <type name="date" parents="abstraction"/>
  <type name="measure" parents="abstraction"/>
  <type name="amt" parents="measure"/>
  <type name="dur" parents="measure"/>
  <type name="num" parents="abstraction"/>
  <type name="time" parents="abstraction"/>
  <type name="location" parents="sem-obj"/>
  <type name="city" parents="location"/>
  <type name="entity" parents="sem-obj"/>
  <type name="causal-agent" parents="entity"/>
  <type name="organization" parents="causal-agent"/>
  <type name="mental-obj" parents="entity"/>
  <type name="phys-obj" parents="entity"/>
  <type name="animate-being" parents="phys-obj"/>
  <type name="person" parents="animate-being causal-agent"/>
  <type name="grouping" parents="sem-obj"/>
  <type name="situation" parents="sem-obj"/>
  <type name="change" parents="situation"/>
  <type name="action" parents="change"/>
  <type name="statement" parents="action"/>
  <type name="motion" parents="change"/>
  <type name="quantification" parents="situation"/>
  <type name="state" parents="situation"/>
  <type name="proposition" parents="state"/>
  <type name="experience" parents="state"/>
  <!-- a structural element in the semantics -->
  <type name="struct"/>
  <!-- additional sorts for flights (builds on ../core-en/types.xml) -->
  <type name="airline" parents="organization"/>
  <type name="airport" parents="location phys-obj"/>
  <type name="fareclass" parents="abstraction"/>
  <type name="scalar" parents="proposition"/>
  <type name="timeframe" parents="abstraction"/>
  <type name="travel" parents="action motion"/>
</types>

=== timhunter/ccpc/dds/openccg/grammars/routes/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file contains the syntactic and semantic simple/atomic types.

The syntactic values for person are defined under pers-vals, and the
semantic types/sorts are defined under sem-obj. Indenting shows the
structure of the hierarchy. (In the general case, multiple parents may
be specified.)

Copyright (C) 2006 Michael White
$Revision: 1.4 $, $Date: 2006/05/20 20:34:16 $ 
-->
<types 
  name="tiny"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="../types.xsd"
>

  <!-- person vals -->
  <type name="pers-vals"/>
  <type name="3rd" parents="pers-vals"/>
  <type name="non-3rd" parents="pers-vals"/>
    <type name="1st" parents="non-3rd"/>
    <type name="2nd" parents="non-3rd"/>

  <!-- ontological sorts -->
  <type name="sem-obj"/>
    <type name="abstraction" parents="sem-obj property"/>
      <type name="direction" parents="abstraction location"/>
      <type name="measure" parents="abstraction"/>
        <type name="amt" parents="measure"/>
        <type name="dur" parents="measure"/>
        <type name="dist" parents="measure"/>
      <type name="num" parents="abstraction"/>
      <type name="ord" parents="abstraction"/>
      <type name="time" parents="abstraction"/>
    <type name="location" parents="sem-obj property"/>
      <type name="city" parents="location"/>
      <type name="place" parents="location"/>
    <type name="path" parents="sem-obj"/>
    <type name="phys-obj" parents="sem-obj"/>
      <type name="animate-being" parents="phys-obj"/>
        <type name="person" parents="animate-being"/>
      <type name="thing" parents="phys-obj"/>
        <type name="landmark" parents="thing location"/>
        <type name="road" parents="thing location"/>
	  <type name="property" parents="sem-obj"/>
    <type name="situation" parents="sem-obj"/>
      <type name="change" parents="situation"/>
        <type name="action" parents="change"/>
          <type name="turn" parents="action"/>
      <type name="state" parents="situation"/>

  <!--
	<type name="sem-obj"/>
    <type name="abstraction" parents="sem-obj"/>
      <type name="date" parents="abstraction"/>
      <type name="measure" parents="abstraction"/>
        <type name="amt" parents="measure"/>
        <type name="dur" parents="measure"/>
      <type name="num" parents="abstraction"/>
      <type name="time" parents="abstraction"/>
    <type name="location" parents="sem-obj"/>
      <type name="city" parents="location"/>
    <type name="entity" parents="sem-obj"/>
      <type name="causal-agent" parents="entity"/>
        <type name="organization" parents="causal-agent"/>
      <type name="mental-obj" parents="entity"/>
      <type name="phys-obj" parents="entity"/>
        <type name="animate-being" parents="phys-obj"/>
          <type name="person" parents="animate-being causal-agent"/>
    <type name="grouping" parents="sem-obj"/>
    <type name="situation" parents="sem-obj"/>
      <type name="change" parents="situation"/>
        <type name="action" parents="change"/>
          <type name="statement" parents="action"/>
        <type name="motion" parents="change"/>
      <type name="quantification" parents="situation"/>
      <type name="state" parents="situation"/>
        <type name="proposition" parents="state"/>
        <type name="experience" parents="state"/>
  -->  

</types>

=== timhunter/ccpc/dds/openccg/grammars/mini-nezperce/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
      - This file is generated by parametric-types.xsl from parameter specs
	    (parameters.xml) to set up  types.xml file for development.
         
      - If the language in question has eg. quirky subjects etc., add their 
	    values under appropriate types.
	 
	 -->
<!--
	   subject-case, s-case, p-case and a-case are pre-defined types that are
	   used in the automatically generated initial lexicon (preset-families
	   .xml). We recommend that you dont change them. They handle
	   accusative/ergative mapping among other things (cf. types.xml initial
	   hierarchy).
	  
	 -->
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../types.xsd" name="Nez Perce">
  <type name="s-case" parents="subject-case"/>
  <type name="subject-case"/>
  <type parents="s-case" name="nom"/>
  <!--
		 Warning: Please substitute case names as children
		of a-case and p-case since these cannot be predicted parametrically
		for an unaligned language (cf. unknown and unknown2 values)
        -->
  <type parents="a-case" name="unknown"/>
  <type name="a-case"/>
  <type parents="p-case" name="unknown2"/>
  <type name="p-case"/>
</types>

=== timhunter/ccpc/dds/openccg/grammars/comic/types-extras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2003-4 University of Edinburgh (Michael White)
$Revision: 1.3 $, $Date: 2004/11/21 14:22:18 $ 
-->
<types name="comic" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="../types.xsd"
>

  <!-- additional sorts for comic (builds on ../core-en/types.xml) -->
  <type name="colour" parents="abstraction proposition"/>
  <type name="colour_prop" parents="proposition"/>
  <type name="decoration" parents="phys-obj"/>
  <type name="manufacturer" parents="organization"/>
  <type name="quality" parents="proposition"/>
  <type name="series" parents="abstraction proposition"/>
  <type name="size" parents="abstraction proposition"/>
  <type name="style" parents="abstraction proposition"/>
  
</types>

=== timhunter/ccpc/dds/openccg/grammars/tiny/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file contains the syntactic and semantic simple/atomic types.

The syntactic values for person are defined under pers-vals, and the
semantic types/sorts are defined under sem-obj. Indenting shows the
structure of the hierarchy. (In the general case, multiple parents may
be specified.)

Copyright (C) 2005 University of Edinburgh (Michael White)
$Revision: 1.1 $, $Date: 2005/01/22 12:53:35 $ 
-->
<types 
  name="tiny"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="../types.xsd"
>

  <!-- person vals -->
  <type name="pers-vals"/>
  <type name="3rd" parents="pers-vals"/>
  <type name="non-3rd" parents="pers-vals"/>
    <type name="1st" parents="non-3rd"/>
    <type name="2nd" parents="non-3rd"/>

  <!-- ontological sorts -->
  <type name="sem-obj"/>
    <type name="phys-obj" parents="sem-obj"/>
      <type name="animate-being" parents="phys-obj"/>
        <type name="person" parents="animate-being"/>
      <type name="thing" parents="phys-obj"/>
    <type name="situation" parents="sem-obj"/>
      <type name="change" parents="situation"/>
        <type name="action" parents="change"/>
      <type name="state" parents="situation"/>

</types>
